on:
  push:
    branches: ["master"]

jobs:
  run-npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: npm install and build webpack
        run: |
          pwd
          ls -la ..
          npm install
          npm run build

  run-npm-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: npm deploy
        run: npm run deploy
